name: Package

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  package:
    name: Package
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm i

      - name: Package
        run: npm run package

      - name: Upload artifact to action
        uses: actions/upload-artifact@v4
        with:
          path: |
            *.vsix
