name: Package & Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Package & Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - id: get-version
        run: tag="${{ github.ref }}"; version=${tag#"refs/tags/v"}; echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm i

      - name: Install vsce
        run: npm i -g vsce

      - name: Package
        run: vsce package

      - name: Upload artifact to action
        uses: actions/upload-artifact@v4
        with:
          path: |
            *.vsix

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vuengine-language-server-${{steps.get-version.outputs.version}}.vsix
          asset_name: vuengine-language-server-${{steps.get-version.outputs.version}}.vsix
          asset_content_type: application/vsix
